const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

// Load configuration
const ASSETS = require('./assets-config.json');

async function processAssets() {
    const tempDir = 'temp_assets';
    if (!fs.existsSync(tempDir)) {
        console.error("Temp directory not found. Please move generated assets there.");
        return;
    }

    const files = fs.readdirSync(tempDir);
    let processedCount = 0;

    for (const asset of ASSETS) {
        // Look for a file that starts with the asset ID
        const sourceFile = files.find(f => f.startsWith(asset.id) && f.endsWith('.png'));

        if (!sourceFile) {
            // It's okay if not all assets are present, we might be processing a batch
            continue;
        }

        const sourcePath = path.join(tempDir, sourceFile);
        const destDir = path.resolve(asset.destDir);

        if (!fs.existsSync(destDir)) {
            fs.mkdirSync(destDir, { recursive: true });
        }

        // Check if destination already exists to avoid re-processing if not needed
        // (Optional: for now we overwrite to ensure latest version)

        console.log(`Processing ${asset.baseName}...`);

        try {
            const image = sharp(sourcePath);
            const metadata = await image.metadata();

            // Calculate dimensions
            const width2x = asset.baseSize2x;
            const width3x = Math.floor(width2x * 1.5);

            // Generate @3x
            await image
                .clone()
                .resize(width3x)
                .toFile(path.join(destDir, `${asset.baseName}@3x.png`));

            // Generate @2x
            await image
                .clone()
                .resize(width2x)
                .toFile(path.join(destDir, `${asset.baseName}@2x.png`));

            // Generate JSON Metadata
            const jsonMeta = {
                name: asset.baseName,
                type: asset.type,
                dimensions: {
                    "@2x": { width: width2x, height: "auto" },
                    "@3x": { width: width3x, height: "auto" }
                },
                generatedAt: new Date().toISOString(),
                notes: "Generated by AI. Transparency may need manual refinement."
            };

            fs.writeFileSync(
                path.join(destDir, `${asset.baseName}.json`),
                JSON.stringify(jsonMeta, null, 2)
            );

            console.log(`Finished ${asset.baseName}`);
            processedCount++;
        } catch (err) {
            console.error(`Error processing ${asset.baseName}:`, err);
        }
    }

    console.log(`\nBatch complete. Processed ${processedCount} assets.`);
}

processAssets().catch(console.error);
